name: Maven Build and Release

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0" # 每周日午夜运行
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build with Maven
        run: mvn clean package --batch-mode
      - name: Get Last Commit Message
        id: commit_message
        uses: actions/github-script@v6
        with:
          script: |
            const commits = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              per_page: 1
            });
            console.log(commits.data[0].commit.message);
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          title: imageapi
          body: |
            Changes in this release:
            - ${{ steps.commit_message.outputs.message }}
          draft: false
          prerelease: false
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          repo: it985/${{ github.ref }} # defaults to current repo
          keep_latest: 1
        #           delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}