name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN  }}
        run: |
          # Get commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Build and push Docker image
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker build -t study996/imageapi:${COMMIT_HASH} .
          docker push study996/imageapi:${COMMIT_HASH}


#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Build and push Docker image
#        env:
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#        run: |
#          # 获取commit hash
#          COMMIT_HASH=$(git rev-parse HEAD)
#
#          # 构建和推送Docker镜像
#          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
#          docker buildx build --platform study996/imageapi -t imageapi:${COMMIT_HASH} --push .
