name: Sync README to Docker Hub
on:
  push:
    branches:
      - master  # 替换为您的主分支名称

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync README to Docker Hub
        run: |
          cat README.md > README-dockerhub.md
          docker run --rm -v "$(pwd):/workspace" -w /workspace \
            python:3-alpine sh -c "pip install -U twine && twine upload --skip-existing README-dockerhub.md"
          cat dist/README-dockerhub.md
